name: timirama
description: "Clz Project.."



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  
  

  get: ^4.7.2

  flutter_screenutil: ^5.9.3
  google_sign_in: ^7.1.0
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  permission_handler: ^12.0.1
  cloud_firestore: ^5.6.7
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  
  path_provider: ^2.1.5
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  step_progress_indicator: ^1.0.2
  bottom_picker: ^3.2.0
  choice: ^2.3.2
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  google_nav_bar: ^5.0.7
  cloudinary_public: ^0.23.1
  line_icons: ^2.0.3
  cached_network_image: ^3.4.1
  firebase_database: ^11.3.6
  hugeicons: ^0.0.11
  flutter_advanced_avatar: ^1.5.2
  flutter_card_swiper: ^7.0.2
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.2
  badges: ^3.1.2
  chat_bubbles: ^1.7.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  flutter_slidable: ^4.0.0
  flutter_platform_widgets: ^9.0.0

  camerawesome: ^2.5.0
  google_fonts: ^6.2.1
  video_trimmer: ^5.0.0
  video_player: ^2.8.1
  dropdown_button2: ^2.3.9
  waveform_recorder: ^1.7.0
  voice_message_package: ^2.2.1
  uuid: ^4.5.1
  quickalert: ^1.1.0
  contained_tab_bar_view: ^0.8.0
  hydrated_bloc: ^10.1.1

  shimmer: ^3.0.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.1
  logger: ^2.6.1







dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.0
  
  
  
  
  
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner:
  bloc_lint: 0.2.0

dependency_overrides:
  rxdart: ^0.27.7 
  intl: ^0.20.2





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
    
  
  
  
  
  
  
  
  
