// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxusJJWvp2UaLkrbeC30LklFEy4hIhGw',
    appId: '1:163966635802:web:615130658e7bc8a141a6a3',
    messagingSenderId: '163966635802',
    projectId: 'timirama-3c220',
    authDomain: 'timirama-3c220.firebaseapp.com',
    storageBucket: 'timirama-3c220.firebasestorage.app',
    measurementId: 'G-V246SE4KF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ5k9fTL-geumpUYvyYb26g3Cb5e9mpwA',
    appId: '1:163966635802:android:553405385db61a4841a6a3',
    messagingSenderId: '163966635802',
    projectId: 'timirama-3c220',
    storageBucket: 'timirama-3c220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFewfTB3_6KUoEmy0TCtDhr3q4se1Vao',
    appId: '1:163966635802:ios:8d0081e1bcb545c241a6a3',
    messagingSenderId: '163966635802',
    projectId: 'timirama-3c220',
    storageBucket: 'timirama-3c220.firebasestorage.app',
    iosBundleId: 'com.example.timirama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFewfTB3_6KUoEmy0TCtDhr3q4se1Vao',
    appId: '1:163966635802:ios:8d0081e1bcb545c241a6a3',
    messagingSenderId: '163966635802',
    projectId: 'timirama-3c220',
    storageBucket: 'timirama-3c220.firebasestorage.app',
    iosBundleId: 'com.example.timirama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtxusJJWvp2UaLkrbeC30LklFEy4hIhGw',
    appId: '1:163966635802:web:3e503bd61668d16741a6a3',
    messagingSenderId: '163966635802',
    projectId: 'timirama-3c220',
    authDomain: 'timirama-3c220.firebaseapp.com',
    storageBucket: 'timirama-3c220.firebasestorage.app',
    measurementId: 'G-PNM2JG1H9J',
  );

}